#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
if (( 10#${ENSMEM:-0} > 0 )); then
  source "${HOMEgfs}/ush/jjob_header.sh" -e "landensanl" -c "base landanl landensanl"
  export CASE=${CASE_ENS}
else
  source "${HOMEgfs}/ush/jjob_header.sh" -e "landanl" -c "base landanl"
fi

##############################################
# Begin JOB SPECIFIC work
##############################################

# Restart conditions for GFS cycle come from GDAS
rCDUMP=${RUN}
[[ ${RUN} == "gfs" ]] && export rCDUMP="gdas"

# Get OBS for ENKFGDAS run from GDAS
oCDUMP=${RUN}
[[ ${RUN} == "enkfgdas" ]] && export oCDUMP="gdas"

# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
declare -rx GDATE
# shellcheck disable=
declare -rx gPDY="${GDATE:0:8}"
declare -rx gcyc="${GDATE:8:2}"

# Construct COM variables from templates (see config.com)
RUN=${oCDUMP} YMD=${PDY} HH=${cyc} generate_com -x COM_OBS
YMD=${PDY} HH=${cyc} generate_com -rx COM_LAND_ANALYSIS COM_CONF

RUN=${rCDUMP} YMD=${gPDY} HH=${gcyc} generate_com -rx \
    COM_ATMOS_RESTART_PREV:COM_ATMOS_RESTART_TMPL

mkdir -m 775 -p "${COM_LAND_ANALYSIS}" "${COM_CONF}"

###############################################################
# Run relevant script
###############################################################
${SNOWANLPY:-${SCRgfs}/exglobal_land_analysis.py}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
