#! /usr/bin/env bash

source "${HOMEgfs}/ush/preamble.sh"
if (( 10#${ENSMEM:-0} > 0 )); then
  source "${HOMEgfs}/ush/jjob_header.sh" -e "esno" -c "base snowanl esno"
  export CASE=${CASE_ENS}
else
  source "${HOMEgfs}/ush/jjob_header.sh" -e "snowanl" -c "base snowanl"
fi

# Restart conditions for GFS cycle come from GDAS
rCDUMP=${RUN}
[[ ${RUN} == "gfs" ]] && export rCDUMP="gdas"

# Get OBS for ENKFGDAS run from GDAS
oCDUMP=${RUN}
[[ ${RUN} == "enkfgdas" ]] && export oCDUMP="gdas"

##############################################
# Set variables used in the script
##############################################
# Ignore possible spelling error (nothing is misspelled)
# shellcheck disable=SC2153
GDATE=$(date --utc +%Y%m%d%H -d "${PDY} ${cyc} - ${assim_freq} hours")
gPDY=${GDATE:0:8}
gcyc=${GDATE:8:2}

##############################################
# Begin JOB SPECIFIC work
##############################################
# Generate COM variables from templates
RUN=${oCDUMP} YMD=${PDY} HH=${cyc} generate_com -x COM_OBS
YMD=${PDY} HH=${cyc} generate_com -rx COM_SNOW_ANALYSIS COM_CONF

RUN=${rCDUMP} YMD=${gPDY} HH=${gcyc} generate_com -rx \
    COM_ATMOS_RESTART_PREV:COM_ATMOS_RESTART_TMPL

mkdir -m 775 -p "${COM_SNOW_ANALYSIS}" "${COM_CONF}"

###############################################################
# Run relevant script

EXSCRIPT=${SNOWANLPY:-${HOMEgfs}/scripts/exglobal_snow_analysis.py}
${EXSCRIPT}
status=$?
[[ ${status} -ne 0 ]] && exit "${status}"

##############################################
# End JOB SPECIFIC work
##############################################

##############################################
# Final processing
##############################################
if [[ -e "${pgmout}" ]] ; then
  cat "${pgmout}"
fi

##########################################
# Remove the Temporary working directory
##########################################
cd "${DATAROOT}" || true
[[ ${KEEPDATA} = "NO" ]] && rm -rf "${DATA}"

exit 0
